### ISSUE TITLE
Flea3 outputs green image

### ISSUE THREAD

**Issue by jeff-o** [ros-drivers/pointgrey_camera_driver#101]
On two recently purchased USB3 Flea3 cameras, the image produced when using the default camera.launch file is always green-tinted. No matter what the start-up conditions (low light, high light, etc) the image starts and remains green.

We discovered that adding a parameter for auto_white_balance = false to the launch file seems to correct this behaviour. This never used to be necessary, so something must have changed in the hardware or driver. I don't mind adding this param into the launch file, but it's preferable if the issue were corrected at the root.

**Comment by mikepurvis** [comment]
A PR related to this was recently merged (#95). Can you please try with the driver built from source and see if the issue remains?

**Comment by stevendaniluk** [comment]
Since you haven't received any response, I'll mention that I was also experiencing the same green screen problem with a USB3 Blackfly camera , but building from source with the white balance changes updates PR #95 resolved it.

**Comment by mikepurvis** [comment]
Excellent. Thanks, @stevendaniluk.
