### ISSUE TITLE
Kinetic package missing from repo

### ISSUE THREAD

**Issue by gkguru** [ros-drivers/pointgrey_camera_driver#113]
I tried ``apt-get install ros-kinetic-pointgrey-camera-driver`` to install the package but got the following error:
```
E: Unable to locate package ros-kinetic-pointgrey-camera-driver
```

**Comment by gkguru** [comment]
``apt-cache search pointgrey`` yields only ``ros-kinetic-pointgrey-camera-description``
```
ros-kinetic-pointgrey-camera-description - A series of URDF driver decriptions for Point Grey cameras
```

**Comment by mikepurvis** [comment]
Things are looking happier now: http://repositories.ros.org/status_page/ros_kinetic_default.html?q=pointgrey

**Comment by JustBenj** [comment]
Missing again as of 8pm June 7, 2019. Same results as the original issue. Is it related to https://discourse.ros.org/t/new-gpg-keys-deployed-for-packages-ros-org/9454?

**Comment by rubenanapu** [comment]
As of today, 10th of June, 2019, the error is happening again.

**Comment by djhanove** [comment]
I'm having these same issues when i use the command apt-get install ros-kinetic-pointgrey-camera-driver.
I'm using 16.04, x86

**Comment by thefinaljob** [comment]
Missing again as of June 27th, 2019, can someone fix this asap?

**Comment by thefinaljob** [comment]
@mikepurvis

**Comment by alvikag** [comment]
I am facing the same issue. I am using ros kinetic, ubuntu 16.04

**Comment by mtfurlan** [comment]
This issue came up higher in google, so for for the next person to come along:
Look at #187 for the reason and #188 for a janky snapshot workaround.
