### ISSUE TITLE
FlyCapture2::ErrorType 41 Image consistency issue

### ISSUE THREAD

**Issue by ashnarayan13** [ros-drivers/pointgrey_camera_driver#124]
I am working with BFLY PGE 12A2M-CS cameras. I am able to run them on Linux x86 PC's but on an arm8 Jetson TX1, I get the following error. I have set the bandwidth to the maximum from the Ptgrey settings. But this does not help.

Any suggestions?

**Comment by vmatos** [comment]
Have you played around with FlyCap2? See first if you can get there the desired performance and frame rate.

Then use the same settings in the ROS driver.
