### ISSUE TITLE
How do i use this driver for Blackfly S point grey camera?

### ISSUE THREAD

**Issue by sumitspattan** [ros-drivers/pointgrey_camera_driver#159]
Hello,

How do i use this driver for blackfly s model?

**Comment by lab135-ncepu** [comment]
i have the same problem.

**Comment by sumitspattan** [comment]
@fabrizioschiano  Since the driver which is currently implemented is using FlyCapture SDK, is it possible to implement the same driver for Spinnaker SDK? 

Or

is it possible to use the existing driver for Blackfly S camera, Model: BFS-PGE-50S5C ? 

If I download the existing ros driver, it won't work. As said by  @jzx-gooner

**Comment by nflsalex** [comment]
Same here, how do we make it work for Blackfly S?

**Comment by DrCurry** [comment]
BlackFly S only supports Spinnaker. This driver uses FlyCapture. If you want to use BlackFly S, you are going to have to write your own node wrapping the Spinnaker SDK with ROS

**Comment by mhosmar-cpr** [comment]
Hi all, I have been working on a Spinnaker driver which I have tested working with Blackfly S (BFS-U3-32S4M) and Chameleon 3.  Check it out over at https://github.com/ros-drivers/flir_camera_driver. It is based on pointgrey_camera_driver and should look fairly familiar.  If there are any issues specific to your camera I encourage you to contribute fixes. I hope that eventually we will be able to support all the new FLIR cameras.
