### ISSUE TITLE
Build no longer works as pointgrey changed their website.

### ISSUE THREAD

**Issue by mincrmatt12** [ros-drivers/pointgrey_camera_driver#187]
They now use "Box" to distribute their files, which doesn't seem to have static links.

**Comment by ibtaylor** [comment]
Probably not cool to let everyone use the same credentials anyway. 
https://github.com/ros-drivers/pointgrey_camera_driver/blob/6c3e4cb82f67e00980fce33bdc4d4fb251a4a06b/pointgrey_camera_driver/cmake/download_flycap#L38-L41

**Comment by mincrmatt12** [comment]
I mean, I've discovered recently that BOX has its own API, so we should be able to make a service account and store its credentials in the repo.

**Comment by tonybaltovski** [comment]
This has been fixed finally!
