### ISSUE TITLE
Cannot Download Camera Driver

### ISSUE THREAD

**Issue by thefinaljob** [ros-drivers/pointgrey_camera_driver#189]
Hello There,

As other users have pointed out, we are unable to successfully install the driver using sudo. We are getting the following error.

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-lunar-pointgrey-camera-driver`

I was wondering if it would be possible for this issue to be rectified.

**Comment by hcyoo93** [comment]
I have same problem
How did you resolve this issue?

**Comment by LukeAI** [comment]
+1

**Comment by anakin0620** [comment]
https://github.com/ros-drivers/pointgrey_camera_driver/issues/188#issuecomment-521527548

**Comment by tonybaltovski** [comment]
Has been released for Kinetic and Melodic.  Lunar is EOL.

**Comment by LukeAI** [comment]
@tonybaltovski 

The same issue applies to Kinetic. The [wiki ](http://wiki.ros.org/pointgrey_camera_driver) advises: "sudo apt-get install ros-kinetic-pointgrey-camera-driver"

but no such package exists.

**Comment by tonybaltovski** [comment]
It hasn't been synced to [main](http://repositories.ros.org/status_page/kinetic_default.html) yet, you can add the [ros-shadow-fixed](http://wiki.ros.org/action/show/TestingRepository?action=show&redirect=ShadowRepository) if you want the deb.
