### ISSUE TITLE
Default configuration not loading

### ISSUE THREAD

**Issue by pedropgusmao** [ros-drivers/pointgrey_camera_driver#19]
Hi,

Please, I set the default value of video_mode in PointGrey.cfg to format7_mode1 as in: 

gen.add("video_mode", str_t, SensorLevels.RECONFIGURE_STOP, "Video mode.", "format7_mode1", edit_method = video_modes)

but the camera keeps loading format7_mode0.

Is there a way for the camera to load these parameters at launch time?

Thanks,
Pedro

**Comment by mikepurvis** [comment]
You can specify them using `<param>` tags in your roslaunch, eg:

https://github.com/ros-drivers/pointgrey_camera_driver/blob/3fe1e8b3814891cba3ba2aee1fc0aff4b0081120/pointgrey_camera_driver/launch/bumblebee.launch#L16
