### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Tobias-Fischer** [ros-drivers/pointgrey_camera_driver#200]
Hiya, is it possible to release this package for ROS noetic?

**Comment by bostoncleek** [comment]
Hi I am also interested in the noetic release.

**Comment by Tobias-Fischer** [comment]
Ping @tonybaltovski

**Comment by tonybaltovski** [comment]
@Tobias-Fischer have you tested this on Focal yet?  There doesn't seem to be FlyCapture2 SDK available from FLIR.

**Comment by bostoncleek** [comment]
@tonybaltovski I am running it on Focal. Installing the FlyCapture2 SDK for Bionic will work.

**Comment by tonybaltovski** [comment]
Thanks @bostoncleek. Sorry for the delay folks, had to get hosting server updated. Bloomed here: https://github.com/ros/rosdistro/pull/27262.
