### ISSUE TITLE
Usage of uint16_t

### ISSUE THREAD

**Issue by versatran01** [ros-drivers/pointgrey_camera_driver#37]
Is there any particular reason for using uint16_t instead of just unsigned?
e.g. bool PointGreyCamera::setWhiteBalance(uint16_t &blue, uint16_t &red)

**Comment by mikepurvis** [comment]
No particular reason, but note that the `blue` and `red` values get bit-shifted into a single 32-bit register, so there'd be nothing gained from them being larger types.
