### ISSUE TITLE
Image wrong "shifted/cropped"

### ISSUE THREAD

**Issue by samuelba** [ros-drivers/pointgrey_camera_driver#43]
sometimes it happens that the image is cropped the wrong way, like the image below:

![pointgrey_issue](https://cloud.githubusercontent.com/assets/3610764/8255028/5e2a47ae-169d-11e5-88f4-02f1079a2efc.png)

however, if I unsubscribe and resubscribe to the image topic, that can change. So after resubscribing the image can be cropped right or wrong, it's random.

I use Ubuntu 14.04 and the cameras are connected to USB 3.0

**Comment by gnarang1024** [comment]
Hey, did you find a solution to this? I'm seeing the same behavior with my Chameleon 3 CM3-U3-13Y3C-CS sensor. Thanks!

**Comment by samuelba** [comment]
After a driver update (don't remember which one) it worked without problems.
