### ISSUE TITLE
Not detecting Bumbleebee2

### ISSUE THREAD

**Issue by mcross8** [ros-drivers/pointgrey_camera_driver#6]
Hello,

I'm following the instructions on http://wiki.ros.org/pointgrey_camera_driver for using the Bumblebee2 camera. Packages install quite happily. However, when attempting to list the cameras, 'rosrun pointgrey_camera_driver list_cameras', it doesn't find the connected device. The prompt suggests to restart udev and replug the camera. 

It's at this point that nothing changes; the attached camera isn't found. When I 'udevadm monitor', it shows the device being removed, and then added, when I unplug and replug in the camera. 

I can run the camera1394stereo package and it connects happily enough; however I'm interested in trying this package because, well, I'm using it with products from Clearpath!

I guess my 2 questions are:

1) What is the package looking for when attempting to list cameras? Mine shows up as 'fw1' in /dev. 

2) What else am I doing wrong?

Thanks!
Matt

**Comment by l0g1x** [comment]
Im not sure if this is just something with my computer, but i am still receiving the same error on Ubuntu 14.04 indigo. I can reproduce 

sudo su
source /opt/ros/hydro/setup.bash
rosrun pointgrey_camera_driver list_cameras

and it works fine. Coriander works perfectly fine too, and so does camera1394stereo. udevinfo doesnt work for me on 14.04 and udevadm doesnt produce the useful attributes like udevinfo does.

device shows up under /dev/fw1 as well. Not sure what to do here.

**Comment by sumitveerawal** [comment]
I am also facing the same problem for Ubuntu 12.04.
I have installed ros-hydro driver "pointgrey_camera_driver". When I try to run the nodes to connect to the camera, I am getting the following error messages (with and with out specifying serial number): 

1. PointGreyCamera::connect Failed to get first connected camera | FlyCapture2::ErrorType 19Failed to get the camera from the index
2.  PointGreyCamera::connect Could not find camera with serial number: 10210007. Is that camera plugged in? | FlyCapture2::ErrorType 19Failed to get the camera from the serial number.

What is surprising is that if I am running everything as a superuser, I am able to access cameras properly with no errors.

What am I doing wrong, please help me out here.

My /lib/udev/rules.d contains the standard file 40-ros-hydro-pointgrey-camera-driver.rules:-
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2000", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2001", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2002", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2003", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2004", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="2005", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3000", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3001", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3004", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3005", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3006", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3007", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3008", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="300A", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="300B", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3100", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3101", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3102", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3103", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3104", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3105", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3106", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3107", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3108", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3109", MODE="0666", GROUP="pgrimaging"
ATTRS{idVendor}=="1e10", ATTRS{idProduct}=="3300", MODE="0666", GROUP="pgrimaging"
KERNEL=="raw1394", MODE="0666", GROUP="pgrimaging"
KERNEL=="video1394*", MODE="0666", GROUP="pgrimaging"
KERNEL=="fw*", SUBSYSTEM=="firewire", ATTR{vendor}=="0x00b09d", MODE="0666", GROUP="pgrimaging"
KERNEL=="fw*", SUBSYSTEM=="firewire", ATTR{vendor}=="0x00a02d", MODE="0666", GROUP="pgrimaging"
