### ISSUE TITLE
PointGrey SDK has been updated, possibly causing cmake to fail to compile. 

### ISSUE THREAD

**Issue by msy22** [ros-drivers/pointgrey_camera_driver#64]
I've been trying the tutorials found here: 

http://www.clearpathrobotics.com/assets/guides/ros/ROS%20Navigation%20Basics.html

which involves downloading and installing pointgrey_camera_driver. However, cmake fails to compile the package, because either the SDK or the headers are not being downloaded and installed properly (i'm not sure which). I noticed that the SDK was updated from version 2.9.3.**13** to 2.9.3.**43** on 27/04/2016 - less than a week ago, and I believe this is part of the problem. See here for more info: 

http://answers.ros.org/question/233456/jackal-tutorial-no-longer-builds-properly/  

Regardless, the problem can be solved by manual installing the 2.9.3.43 SDK

**Comment by tonybaltovski** [comment]
I had the same issue.
