### ISSUE TITLE
how to get /tf from pointgrey

### ISSUE THREAD

**Issue by zfxw0206** [ros-drivers/pointgrey_camera_driver#78]
Now I want to use a blackfly GigE 3.0 camera and [ar_track_alvar](http://wiki.ros.org/ar_track_alvar) to track a marker. Then I need a /tf which comes from the camera. Does anybody know how to do it?

Thank you!

**Comment by mikepurvis** [comment]
You can specify the `frame_id` you want as a standard parameter, eg:

https://github.com/ros-drivers/pointgrey_camera_driver/blob/0bcd3c54320f7265069686801f441a3592e7f4c7/pointgrey_camera_driver/launch/bumblebee.launch#L12

Then you'll need either a static transform publisher or a URDF + robot_state_publisher to get a transform for that specific frame, see: http://wiki.ros.org/urdf/Tutorials
