### ISSUE TITLE
2 cameras can not stream simultaneously

### ISSUE THREAD

**Issue by dani-carbonell** [ros-drivers/pointgrey_camera_driver#8]
Ubuntu 12.04 - ROS hydro - Camera PointGrey BFLY-PGE-13E4C-CS

I run this:
roslaunch pointgrey_camera_driver camera.launch camera_serial:=14212370
roslaunch pointgrey_camera_driver camera.launch camera_serial:=13421083

Both fail with the following outputs:

The first I run-----------
 [camera/camera_nodelet_manager-2] process has died [pid 19061, exit code -11, cmd /opt/ros/hydro/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/dardo/.ros/log/9f92dc46-17d0-11e4-9d36-448a5b417b29/camera-camera_nodelet_manager-2.log].
log file: /home/dardo/.ros/log/9f92dc46-17d0-11e4-9d36-448a5b417b29/camera-camera_nodelet_manager-2*.log
[camera/camera_nodelet-3] process has finished cleanly

The second ------------

[ERROR] [1406714557.804578351]: Failed to find nodelet with name '/camera/camera_nodelet' to unload.
[ERROR] [1406714558.084333320]: Failed to find nodelet with name '/camera/image_proc_debayer' to unload.
[camera/camera_nodelet-2] process has finished cleanly

Then I modified the camera.launch replacing the namespace of group "camera" with an argument called "camera_name":
```xml
<launch>
  <arg name="camera_serial" default="0" />
  <arg name="camera_name" default="camera" />
  <arg name="calibrated" default="0" />
  <group ns="$(arg camera_name)">
    <node pkg="nodelet" type="nodelet" name="camera_nodelet_manager" args="manager" />

    <node pkg="nodelet" type="nodelet" name="camera_nodelet"
          args="load pointgrey_camera_driver/PointGreyCameraNodelet camera_nodelet_manager" >
      <param name="frame_id" value="camera" />
      <param name="serial" value="$(arg camera_serial)" />
      
      <!-- Use the camera_calibration package to create this file -->
      <param name="camera_info_url" if="$(arg calibrated)"
             value="file://$(env HOME)/.ros/camera_info/$(arg camera_serial).yaml" />
    </node>

    <node pkg="nodelet" type="nodelet" name="image_proc_debayer"
          args="load image_proc/debayer camera_nodelet_manager">
    </node>
  </group>
</launch>
```
I launch both cameras with different "camera_name" argument :  ... camera_name:=pg1 camera_name:=pg2 and no errors.
But when I run th rqt_gui with two rqt_imageview in orther to see both at the same time I get this error message in both terminals.

.............
[ERROR] [1406715162.555908850]: PointGreyCamera::grabImage Failed to retrieve buffer | FlyCapture2::ErrorType 41There is an image consistency issue with this image.
[ERROR] [1406715162.698881298]: PointGreyCamera::grabImage Failed to retrieve buffer | FlyCapture2::ErrorType 41There is an image consistency issue with this image.
.............

**Comment by ssafarik** [comment]
I have the same problem w/ two flea3 usb3 cameras, any two that I try.

First, the camera.launch needs a modification for <group ns="camera_$(arg camera_serial)"> (and also frame_id) as others have mentioned.  That change made, then...

Second, and the main issue, is that the first camera works fine, the second does not.  One manefestaion has been that StartCapture() never returns, so perhaps it's a libflycapture bug.  I've also seen where it never gets as far as that call, though I haven't yet tracked down where it hangs prior.  

I do have one machine where it runs successfully, but have not determined the difference w/ the nonfunctioning machines.  I'm on Ubuntu 12.04, ros hydro, libflycapture 2.6.3.4 (have also tried 2.7.3.13), pointgrey_camera_driver apt-get'ted and also built from github.  

My "uname -a" says "Linux uf8bc12848b5a5452582c 3.13.0-43-generic #72~precise1-Ubuntu SMP Tue Dec 9 12:14:18 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux"

Can we reopen this issue?

Steve.

**Comment by ssafarik** [comment]
It looks like it was related to the /etc/default/grub param "usbcore.usbfs_memory_mb=1000".  Making extra sure that the setting is correct, running "sudo update-grub", running "sudo modprobe usbcore usbfs_memory_mb=1000", and rebooting, etc, gets it to work.

**Comment by dani-carbonell** [comment]
In my case, I use two Blackfly ethernet cameras, so I guess this solution does not help me. Any idea?

**Comment by SISegwayRmp** [comment]
worked for me as well follow section 1.10 in the following document

http://www.ptgrey.com/Content/Images/Uploaded/Downloads/Firmware/2014/TAN2012007_UsingLinuxUSB3.pdf?

THANKS!

**Comment by SISegwayRmp** [comment]
Hey dani-carbonell, you might also be experiencing memory buffer issues. We had to tune the OS settings to get the bandwidth we required for distributed processing and multiple vision systems (CRL Multisense SL, 2x Flea3 USB3, and 2x IPC pro (for vision and nav)). Assuming you have a Gig NIC, try setting your UDP buffers higher than the defaults for the OS. For UDP rmem_max and wmem_max GigE settings try:

```
echo 16777215 > /proc/sys/net/core/rmem_max
echo 16777215 > /proc/sys/net/core/wmem_max
```

if it works go into  /etc/sysctl.conf and add this to make it permanent: 

```
net.core.rmem_max = 16777215 
net.core.wmem_max = 16777215 
```

-Patrick
www.stanleyinnovation.com

**Comment by mikepurvis** [comment]
This is fantastic, thanks for looking into it @ssafarik and @SISegwayRmp. If someone could take a few minutes to transcribe the relevant details to [the ROS Wiki](http://wiki.ros.org/pointgrey_camera_driver#Troubleshooting), I'd really appreciate it.

Are we clear to re-close the ticket?

**Comment by ssafarik** [comment]
You can close it as far as I'm concerned.

Steve.

**Comment by mikepurvis** [comment]
Okay, thanks again.

**Comment by SISegwayRmp** [comment]
Same here I have done a bunch of testing also closed the other bug I opened which was directly related

PATRICK HUSSEY
Principal Engineer

STANLEY INNOVATION, INC
9 Henry Clay Drive
Merrimack, NH 03054
Direct: 603.689.9724
Fax: 603.882.8818
http://www.stanleyinnovation.com<http://www.stanleyinnovation.com/>
